name: Deployment Excercise 1
on: [push]
jobs:
  deploy:
    runs-one: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test Code
        run: npm test
      - name: Build Code
        run: npm run build
      - name: Deploy to Server
        run: echo "Deploying to server..."